version: '3'

services:
  apiserver:
    build: ./apiserver
    environment:
      - FUWA_ISUO
      - FUWA_SALT
    volumes:
      - ./data:/app/data
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/dist:ro
      - ./data/databases/gallery:/dist/gallery
      - ./data/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - apiserver