version: '3'

services:
  apiserver:
    build: ./apiserver
    volumes:
      - ./dist:/app/dist
      - ./data:/app/data
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./dist:/dist:ro
      - ./data/logs:/var/log/nginx
    links:
      - apiserver